Repository inspektor-gadget/inspektor-gadget, pull requests merged in 2021-09, with the labels that each got.

#270 biolatency: gives std outputs on error
  pkg/gadgets/biolatency/gadget.go
Labels: area/gadgets

#279 dns gadget: stop on error on perf ring buffer
  pkg/gadgets/dns/tracer/tracer.go
Labels: bug

#273 seccomp: fix fd garbage collector issue
  pkg/gadgets/seccomp/tracer/tracer.go
Labels: bug, gadget/seccomp

#122 Docs: Include instructions for minikube
  README.md
  docs/CONTRIBUTING.md
  docs/install.md
Labels: area/documentation

#283 runcfanotify: fix fd double close
  pkg/runcfanotify/runcfanotify.go
Labels: bug

#272 seccomp: generate SeccompProfile for terminated pods
  docs/gadgets/seccomp.md
  pkg/gadgets/seccomp/gadget.go
  pkg/gadgets/seccomp/syscalls.go
  pkg/gadgets/seccomp/syscalls_none.go
  pkg/gadgets/seccomp/tracer/tracer.go
  pkg/resources/samples/trace-seccomp.yaml
Labels: enhancement, area/gadgets, gadget/seccomp

#322 docs: bindsnoop fixes
  docs/guides/bindsnoop.md
Labels: area/documentation

#320 docs: Create initial dns guide
  docs/guides/dns.md
Labels: area/documentation
