Repository inspektor-gadget/inspektor-gadget, pull requests merged in 2022-06, with the labels that each got.

#653 ci/integration-tests: Clean up resources when the workflow run is cancelled
  .github/actions/run-integration-tests/action.yml
  integration/Makefile
  integration/command.go
  integration/integration_test.go
Labels: area/ci, k8s/aro

#709 docs: Fix TOC link
  docs/install.md
Labels: area/documentation

#695 cmd/kubectl-gadget: Avoid repeated code on snapshot gadgets
  cmd/kubectl-gadget/main.go
  cmd/kubectl-gadget/snapshot/process.go
  cmd/kubectl-gadget/snapshot/snapshot.go
  cmd/kubectl-gadget/snapshot/socket.go
  cmd/kubectl-gadget/utils/errors.go
  cmd/kubectl-gadget/utils/flags.go
  pkg/gadgets/process-collector/types/process-collector.go
  pkg/gadgets/socket-collector/types/socket-collector.go
Labels: gadget/socket-collector, gadget/process-collector
