Repository inspektor-gadget/inspektor-gadget, pull requests merged in 2023-01, with the labels that each got.

#1223 gadgets/snapshot/process: Handle showthreads in server side
  cmd/common/snapshot/process.go
  cmd/kubectl-gadget/snapshot/process.go
  cmd/local-gadget/snapshot/process.go
  pkg/gadget-collection/gadgets/snapshot/process/gadget.go
  pkg/gadgets/snapshot/process/tracer/bpf/process-collector.bpf.c
  pkg/gadgets/snapshot/process/tracer/processcollector_bpfel.o
  pkg/gadgets/snapshot/process/tracer/tracer.go
  pkg/gadgets/snapshot/process/tracer/tracer_test.go
  pkg/gadgets/snapshot/process/types/process-collector.go
Labels: gadgets/snapshot/process

#1226 docs/gadgets: Merge kubectl-gadget and local-gadget instructions
  docs/gadgets/advise/network-policy.md
  docs/gadgets/advise/seccomp-profile.md
  docs/gadgets/profile/block-io.md
  docs/gadgets/profile/cpu.md
  docs/gadgets/snapshot/process.md
  docs/gadgets/snapshot/socket.md
  docs/gadgets/top/block-io.md
  docs/gadgets/top/ebpf.md
  docs/gadgets/top/file.md
  docs/gadgets/top/tcp.md
  docs/gadgets/trace/bind.md
  docs/gadgets/trace/capabilities.md
  docs/gadgets/trace/dns.md
  docs/gadgets/trace/exec.md
  docs/gadgets/trace/fsslower.md
  docs/gadgets/trace/mount.md
  docs/gadgets/trace/oomkill.md
  docs/gadgets/trace/open.md
  docs/gadgets/trace/signal.md
  docs/gadgets/trace/sni.md
  docs/gadgets/trace/tcp.md
  docs/gadgets/trace/tcpconnect.md
  docs/gadgets/traceloop.md
  docs/local-gadget.md
Labels: area/documentation

#1247 CI: use job summaries for test reports
  .github/actions/prepare-and-publish-test-reports/action.yml
  .github/actions/run-integration-tests/action.yml
  .github/workflows/inspektor-gadget.yml
  Makefile
  tools/testjson2md/go.mod
  tools/testjson2md/go.sum
  tools/testjson2md/testjson2md.go
Labels: area/ci

#1264 gadgets: Fix networking gadgets on old kernels
  pkg/gadgets/internal/networktracer/tracer.go
Labels: bug
